// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvmwzgizwpzybkmqzdfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2bXd6Z2l6d3B6eWJrbXF6ZGZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NDk1ODAsImV4cCI6MjA2MjIyNTU4MH0.A9bYIG4-w9RJsgw9eGtU54uzuwNHOjYi2p8DHR1tTKg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);